services:
  dind:
    hostname: dind
    image: docker:dind
    privileged: true
    ports:
    - 3000:3000
    environment:
      DOCKER_TLS_VERIFY: 1
    volumes:
    - certs:/certs
  editor:
    image: sselzer/code
    environment:
      DOCKER_HOST: tcp://dind:2376
      DOCKER_TLS_VERIFY: 1
      DOCKER_CERT_PATH: /certs/client
      PASSWORD: workshop
    command: /home/coder/workspace
    ports:
    - 8080:8080
    depends_on:
    - dind
    volumes:
    - certs:/certs
    - ./exercises:/home/coder/workspace
volumes:
  certs: